sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.23.1 

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - export DJANGO_READ_DOT_ENV_FILE=True
 - echo -e "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}\nDJANGO_READ_DOT_ENV_FILE=True\nDJANGO_SETTINGS_MODULE=config.settings.test" > ${TRAVIS_BUILD_DIR}/.env

language: python
python:
  - "3.6"

script:
  - docker-compose -f docker-compose-dev.yml run -e TRAVIS_ENVIRON=${TRAVIS_ENVIRON} --rm django coverage run --source='.' manage.py test

after_success:
  - docker-compose -f docker-compose-dev.yml run -e TRAVIS_ENVIRON=True COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} --rm django coveralls