sudo: required
dist: trusty
before_install:
  - sudo apt-get install apache2-dev
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - coverage run --source='.' manage.py test && coveralls