# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 19:24
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
