# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 17:30
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20180809_1225'),
    ]

    operations = [
        UnaccentExtension()
    ]
