# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_imageestimateconcept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatario',
            name='company',
        ),
        migrations.RemoveField(
            model_name='destinatario',
            name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='sitio',
            name='company',
        ),
        migrations.AddField(
            model_name='sitio',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destinatario',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Cliente'),
            preserve_default=False,
        ),
    ]
