# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 13:22
from __future__ import unicode_literals

import construbot.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20180930_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageestimateconcept',
            name='image',
            field=models.ImageField(upload_to=construbot.core.utils.get_directory_path),
        ),
    ]
