# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0004_auto_20180620_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
