# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20181109_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageestimateconcept',
            options={'verbose_name': 'Imagen_generador', 'verbose_name_plural': 'Imagenes_generadores'},
        ),
    ]
