# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_contrato_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateconcept',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='alto'),
        ),
        migrations.AddField(
            model_name='estimateconcept',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ancho'),
        ),
        migrations.AddField(
            model_name='estimateconcept',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='largo'),
        ),
    ]
