# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20181129_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retenciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='valor')),
                ('tipo', models.CharField(choices=[('AMOUNT', 'Monto'), ('PERCENTAGE', 'Porcentaje')], default='PERCENTAGE', max_length=21)),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='anticipo'),
        ),
        migrations.AddField(
            model_name='retenciones',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Contrato'),
        ),
    ]
