# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20181206_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together=set([('concept_text', 'project')]),
        ),
    ]
