# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20181213_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='mostrar_anticipo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estimate',
            name='mostrar_retenciones',
            field=models.BooleanField(default=False),
        ),
    ]
