# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_auto_20190129_1500'),
        ('proyectos', '0010_auto_20190130_1544'),
    ]

    operations = [
    ]
