# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_merge_20190131_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Units'),
        ),
    ]
