# Generated by Django 2.1.7 on 2019-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_auto_20190305_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageestimateconcept',
            name='size',
            field=models.BigIntegerField(null=True, verbose_name='Tamaño del archivo en kb'),
        ),
    ]
