# Generated by Django 2.1.7 on 2019-04-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_imageestimateconcept_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Units'),
        ),
    ]
