# Generated by Django 2.1.9 on 2019-07-12 13:11

from django.db import migrations


def poblar_vertices(apps, schema_editor):
    Vertices = apps.get_model('proyectos', 'Vertices')
    EstimateConcept = apps.get_model('proyectos', 'EstimateConcept')
    for ec in EstimateConcept.objects.all():
        Vertices.objects.create(
            nombre='V1', largo=ec.largo, ancho=ec.ancho, alto=ec.alto, piezas=1.00, estimateconcept=ec)


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_vertices'),
    ]

    operations = [
        migrations.RunPython(poblar_vertices),
    ]
