# Generated by Django 2.1.9 on 2019-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_eliminacion_alto_ancho_largo_estimateconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrato',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
