# Generated by Django 2.1.9 on 2019-08-07 16:57

import construbot.core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0018_eliminacion_alto_ancho_largo_estimateconcept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato_Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('folio', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=35, null=True)),
                ('fecha', models.DateField()),
                ('contrato_name', models.CharField(max_length=300)),
                ('contrato_shortName', models.CharField(max_length=80)),
                ('status', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=construbot.core.utils.get_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='monto')),
                ('anticipo', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='anticipo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Cliente')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Sitio')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
