# Generated by Django 2.1.9 on 2019-08-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_poblar-MP-tree-path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='path',
            field=models.CharField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
