# Generated by Django 2.1.9 on 2019-08-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_se-cierra-path-para-MP-tree'),
    ]

    operations = [
        migrations.RenameModel('Cliente', 'Contraparte'),
    ]
