# Generated by Django 2.1.9 on 2019-08-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_Renombre_Cliente_a_Contraparte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='cliente',
            new_name='contraparte',
        ),
        migrations.RenameField(
            model_name='destinatario',
            old_name='cliente',
            new_name='contraparte',
        ),
        migrations.AddField(
            model_name='contraparte',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('DESTAJISTA', 'Destajista'), ('SUBCONTRATISTA', 'Subcontratista')], default='CLIENTE', max_length=14),
        ),
    ]
