# Generated by Django 2.1.9 on 2019-09-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_Contraparte_tipo_and_related_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contraparte',
            options={'verbose_name': 'Contraparte', 'verbose_name_plural': 'Contrapartes'},
        ),
    ]
