# Generated by Django 2.1.13 on 2020-10-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0024_auto_20190916_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateconcept',
            name='cuantity_estimated',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='cuantity_estimated'),
        ),
    ]
