from construbot.core.functional_tests_base import FunctionalTest
from django.core.urlresolvers import reverse
from selenium.webdriver.common.action_chains import ActionChains

class TestCorrectView(FunctionalTest):

    def test_correct_view_index_admin(self):
        self.user_login()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]"))
        self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]").click()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//strong[contains(text(), 'Contratos Vigentes')]"))

    def test_create_contrato(self):
        self.user_login()
        self.create_proyect_objects(0)
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]"))
        self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]").click()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Catalogos')]"))
        catalogos = self.browser.find_element_by_xpath("//*[contains(text(), 'Catalogos')]")
        hover = ActionChains(self.browser).move_to_element(catalogos)
        hover.perform()
        self.browser.find_element_by_class_name("oi-bookmark").click()
        self.wait_for(lambda:self.browser.find_element_by_class_name('oi-plus'))
        self.browser.find_element_by_class_name('oi-plus').click()
        self.wait_for(lambda:self.browser.find_element_by_id('id_folio'))
        self.browser.find_element_by_id("id_code").send_keys("PRUEBA-1")
        self.browser.find_element_by_id("id_fecha").click()
        self.browser.find_element_by_id("id_contrato_name").send_keys("PRUEBA DE CONTRATO 1")
        self.browser.find_element_by_id("id_contrato_shortName").send_keys("PDC1")
        self.browser.find_element_by_xpath('//span[@aria-labelledby="select2-id_cliente-container"]').click()
        self.wait_for(lambda:self.browser.find_element_by_class_name('select2-search__field'))
        self.browser.find_element_by_class_name('select2-search__field').send_keys("clie")
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'cliente_1')]"))
        self.browser.find_element_by_xpath("//*[contains(text(), 'cliente_1')]").click()
        self.browser.find_element_by_xpath('//span[@aria-labelledby="select2-id_sitio-container"]').click()
        self.wait_for(lambda:self.browser.find_element_by_class_name('select2-search__field'))
        self.browser.find_element_by_class_name('select2-search__field').send_keys("sitio")
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'sitio_1')]"))
        self.browser.find_element_by_xpath("//*[contains(text(), 'sitio_1')]").click()
        self.browser.find_element_by_id("id_monto").send_keys("10000")
        self.browser.find_element_by_xpath("//button[@type='submit']").click()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//h2[contains(text(), 'Detalle del contrato PRUEBA DE CONTRATO 1')]"))

    def test_contrato_edit(self):
        self.user_login()
        contratos = self.create_proyect_objects(3)
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]"))
        self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]").click()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Catalogos')]"))
        catalogos = self.browser.find_element_by_xpath("//*[contains(text(), 'Catalogos')]")
        hover = ActionChains(self.browser).move_to_element(catalogos)
        hover.perform()
        self.browser.find_element_by_class_name("oi-bookmark").click()
        self.wait_for(lambda:self.browser.find_element_by_class_name('oi-plus'))
        self.browser.find_element_by_xpath("//a[@href='/proyectos/editar/contrato/{0}/']".format(contratos[2].id)).click()
        self.wait_for(lambda:self.browser.find_element_by_id("id_contrato_name"))
        self.browser.find_element_by_id("id_contrato_name").clear()
        self.browser.find_element_by_id("id_contrato_name").send_keys("EDICION NUMERO 1 A CONTRATO")
        self.browser.find_element_by_xpath("//button[@type='submit']").click()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//h2[contains(text(), 'Detalle del contrato EDICION NUMERO 1 A CONTRATO')]"))

    def test_cliente_creation(self):
        self.user_login()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]"))
        self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]").click()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Catalogos')]"))
        catalogos = self.browser.find_element_by_xpath("//*[contains(text(), 'Catalogos')]")
        hover = ActionChains(self.browser).move_to_element(catalogos)
        hover.perform()
        self.browser.find_element_by_xpath("//span[contains(text(), 'Clientes')]").click()
        self.wait_for(lambda:self.browser.find_element_by_class_name('oi-plus'))
        self.browser.find_element_by_class_name('oi-plus').click()
        self.wait_for(lambda:self.browser.find_element_by_id('id_cliente_name'))
        self.browser.find_element_by_id("id_cliente_name").send_keys("CLIENTE DE PRUEBA 1")
        self.browser.find_element_by_xpath("//button[@type='submit']").click()

    def test_sitio_creation(self):
        self.user_login()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]"))
        self.browser.find_element_by_xpath("//*[contains(text(), 'Proyectos')]").click()
        self.wait_for(lambda:self.browser.find_element_by_xpath("//*[contains(text(), 'Catalogos')]"))
        catalogos = self.browser.find_element_by_xpath("//*[contains(text(), 'Catalogos')]")
        hover = ActionChains(self.browser).move_to_element(catalogos)
        hover.perform()
        self.browser.find_element_by_class_name("oi-map-marker").click()
        self.wait_for(lambda:self.browser.find_element_by_class_name('oi-plus'))
        self.browser.find_element_by_class_name('oi-plus').click()
        self.wait_for(lambda:self.browser.find_element_by_id('id_sitio_name'))
        self.browser.find_element_by_id("id_sitio_name").send_keys("SITIO DE PRUEBA 1")
        self.browser.find_element_by_id('id_sitio_location').send_keys("LOCACION DE PRUEBA 1")
        self.browser.find_element_by_xpath("//button[@type='submit']").click()
