# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180930_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_supervised',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_creation',
        ),
    ]
