# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_nivelacceso_datamigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel_acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.NivelAcceso'),
        ),
    ]
