# Generated by Django 2.1.7 on 2019-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190323_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
