# Generated by Django 2.1.9 on 2019-07-21 22:03

import os
import uuid
import time

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def generate_upload_id():
    return uuid.uuid4().hex

def default_upload_to(instance, filename):
    filename = os.path.join('', instance.upload_id + '.part')
    return time.strftime(filename)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedCoreUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(default=generate_upload_id, editable=False, max_length=32, unique=True)),
                ('file', models.FileField(max_length=255, upload_to=default_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('offset', models.BigIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Uploading'), (2, 'Complete')], default=1)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ChunkedCoreUpload',
                'verbose_name_plural': 'ChunkedCoreUploads',
            },
        ),
    ]
