# Generated by Django 2.1.9 on 2019-07-24 15:45

import construbot.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedcoreupload',
            name='file',
            field=models.FileField(max_length=255, upload_to=construbot.core.utils.get_directory_path),
        ),
    ]
