# Generated by Django 3.2.14 on 2023-06-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chunked_upload_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChunkedCoreUpload',
        ),
    ]
